version: "3"
services:
     db:
       build: 
            context: ./
            dockerfile: mysql-file
       container_name: WOCCdb
       restart: unless-stopped
       command: --default-authentication-plugin=mysql_native_password
       volumes:
         - ./mysql-data:/var/lib/mysql
       environment: 
         MYSQL_ROOT_PASSWORD: 12345
       ports: 
         - 33010:3306
     phpmyadmin:
       image: phpmyadmin/phpmyadmin
       ports:
         - "8087:80"
       depends_on:
         - db
       environment:
         PMA_HOST: db
         PMA_PORT: 3306
